### ISSUE TITLE
refiner panic at unknown variant `Delegate`

### ISSUE THREAD

**Issue by zhangguyu6** [aurora-is-near/borealis-engine-lib#61]
Version: master

Description
I encountered an error while consuming blocks from AWS using the NEAR Data Lake. It appears that the Delegate type cannot be handled properly. 

```

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown variant `Delegate`, expected one of `CreateAccount`, `DeployContract`, `FunctionCall`, `Transfer`, `Stake`, `AddKey`, `DeleteKey`, `DeleteAccount`", line: 1, column: 962)', /usr/local/cargo/registry/src/[github.com](http://github.com/)-1ecc6299db9ec823/near-lake-framework-0.3.0/src/[s3_fetchers.rs:118](http://s3_fetchers.rs:118/):18
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14
   2: core::result::unwrap_failed
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/[result.rs:1785](http://result.rs:1785/):5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: futures_util::stream::stream::StreamExt::poll_next_unpin
   5: <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next
   6: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: futures_util::stream::stream::StreamExt::poll_next_unpin
   9: futures_util::stream::stream::StreamExt::poll_next_unpin
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: tokio::runtime::task::core::Core<T,S>::poll
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: tokio::runtime::scheduler::current_thread::Context::run_task
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
  15: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  16: tokio::runtime::runtime::Runtime::block_on
  17: aurora_refiner::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

I suspect that the issue might be due to an outdated version of near-lake-framework-rs. I recommend upgrading it to version [v0.7.0](https://github.com/near/near-lake-framework-rs/releases/tag/v0.7.0) or higher， which should handle the Delegate type correctly.

**Comment by birchmd** [comment]
Thanks for the report @zhangguyu6 ! I've opened a PR to update the Near Lake version. https://github.com/aurora-is-near/borealis-engine-lib/pull/63

**Comment by birchmd** [comment]
https://github.com/aurora-is-near/borealis-engine-lib/releases/tag/v0.19.1 released with this change. Please let me know if it solves your issue @zhangguyu6

**Comment by zhangguyu6** [comment]
Thank you for the update! I have tested the borealis-engine-lib v0.19.1 release, and the changes have resolved my issue. I appreciate your help! @birchmd
